### PR TITLE
change source repository

### PR DESCRIPTION
**Pull request by leitu**
git.apache.org was not able to reach, change to github instead.

### CODE REVIEW

**Comment by sunilthorat09** [comment]
Upgrading golang image tag to 1.13-alpine which  has proxy support also resolves this issue.

**Comment by elliott-davis** [comment]
> Upgrading golang image tag to 1.13-alpine which has proxy support also resolves this issue.

This also worked for me (or any docker image with golang 1.13 installed)

**Comment by jamestoyer** [comment]
@leitu was this a problem with building from master? Is it now solved?

**Comment by leitu** [comment]
seems fine now @jamestoyer

**Pull request closed without merging**
