### PR TITLE
Added support to enable contentSynchronisation for github issue 76

### PR DESCRIPTION
**Pull request by AshutoshNirkhe**
Please note only enabled property of the contentSynchronisation JSON is added now.
This pull request will address the issue raised here -
https://github.com/atlassian/terraform-provider-artifactory/issues/76

### CODE REVIEW

**Comment by djsly** [comment]
thanks @AshutoshNirkhe ! 

@jamestoyer  / @ttsangAtlassian  can you guys review ?

**Review by jamestoyer — APPROVED** [review]
@djsly I can +1, but sadly I've no longer got maintainer privileges on this repo anymore 🙁

**Comment by djsly** [comment]
@jamestoyer thanks! do you know if this project is still alive within Atlassian ? I'm guessing you do not work for them anymore :(

**Comment by djsly** [comment]
@jamestoyer thanks! do you know if this project is still alive within Atlassian ? I'm guessing you do not work for them anymore :(

**Comment by ttsangAtlassian** [comment]
@djsly I'm still looking after from the Atlassian side however I'm working from Australia so our timezones might not match up.

**Comment by djsly** [comment]
Thanks for the merge.  Would you have some insight on the expected release process for this provider ?  It seems it hasn’t seen any updates  for a while. :)

**Comment by ttsangAtlassian** [comment]
We've been having some issues recently, I'll have a look at it. Just to set expectations, this provider is used actively internally by Atlassian but we are not providing active support for this outside of our needs. There may be some delays in solving issues.

**Comment by djsly** [comment]
Thanks.  

We are planning to use it more and more so as long as this isn’t a dead project we are open to continue with the contribution. Assuming we could expect some reasonable delay on the releases.

**Comment by ttsangAtlassian** [comment]
@djsly @AshutoshNirkhe I've just cut a new release today that includes these changes. From now on it should be automatic

**Comment by djsly** [comment]
Great. Appreciate this!  Happy to ditch our custom built provider

**Pull request merged**
