### PR TITLE
Add RepoLayoutRef for virtual repositories too

### PR DESCRIPTION
**Pull request by Constantin07**
This PR adds support for repo_layout to virtual repositories too.

```
 $ make testacc
==> Checking that code complies with gofmt requirements...
==> Launching Artifactory in Docker...
42750aa9ca588f0967666b78a5a10cd885505bae48f8177534b20ff115805499
Waiting for Artifactory to start
.
.
.
.
.
.
.
TF_ACC=1 ARTIFACTORY_USERNAME=admin ARTIFACTORY_PASSWORD=password ARTIFACTORY_URL=http://localhost:8080/artifactory \
        go test ./... -v -parallel 20  -timeout 120m
?       github.com/atlassian/terraform-provider-artifactory     [no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGroup_basic
--- PASS: TestAccGroup_basic (0.26s)
=== RUN   TestAccGroup_full
--- PASS: TestAccGroup_full (0.18s)
=== RUN   TestAccLocalRepository_basic
--- PASS: TestAccLocalRepository_basic (0.81s)
=== RUN   TestAccLocalRepository_full
--- PASS: TestAccLocalRepository_full (0.70s)
=== RUN   TestAccPermission_basic
--- PASS: TestAccPermission_basic (0.74s)
=== RUN   TestAccRemoteRepository_basic
--- PASS: TestAccRemoteRepository_basic (0.61s)
=== RUN   TestAccRemoteRepository_full
--- PASS: TestAccRemoteRepository_full (0.71s)
=== RUN   TestAccReplication_full
--- PASS: TestAccReplication_full (1.03s)
=== RUN   TestAccUser_basic
--- PASS: TestAccUser_basic (0.28s)
=== RUN   TestAccUser_full
--- PASS: TestAccUser_full (0.24s)
=== RUN   TestAccVirtualRepository_basic
--- PASS: TestAccVirtualRepository_basic (0.52s)
=== RUN   TestAccVirtualRepository_full
--- PASS: TestAccVirtualRepository_full (0.43s)
PASS
ok      github.com/atlassian/terraform-provider-artifactory/pkg/artifactory     (cached)
artifactory
```

CC @dillon-giacoppo

### CODE REVIEW

**Comment by Constantin07** [comment]
I think the decrypting of license has failed in the pipeline. Can someone have a look ?

**Comment by Constantin07** [comment]
Any updates on this ?

**Comment by dillon-giacoppo** [comment]
It is expected that the IT would fail as the key cannot be decrypted from a fork (for obvious security reasons). I will update the build so it doesn't run IT on PRs. This field is undocumented in the API so I am hesitant to add it. I see there is also a PR for it in the client library. Let me test that first and then I can update this -- my main concern is that this will break existing configurations who do not already change it as it would get set to the default, if this is the case this PR will have to be a part of the next major release.

**Comment by Constantin07** [comment]
@dillon-giacoppo Thanks for getting back. You are right, not documented yet but I see it in GUI and I've tested it locally and it works. I will raise a support request so that JFrog updates the REST API docs.

**Comment by Constantin07** [comment]
@dillon-giacoppo FY: JFrog Support submitted  a documentation change request for this (FYI there are other fields missing too in JSON docs).

**Comment by Constantin07** [comment]
@dillon-giacoppo JFrog has officially updated the documentation.
https://www.jfrog.com/confluence/display/RTF/Repository+Configuration+JSON

**Pull request merged**
